"""Replaceable acquisition providers for Proteus."""

from proteus.providers.base import (
    AnnualSalesLookupRequest,
    CandidateDiscoveryRequest,
    Capability,
    CheckStatus,
    PartLookupRequest,
    ProviderReadiness,
    ReadinessCheck,
    SupplyLookupRequest,
    VehicleParcLookupRequest,
)
from proteus.providers.adapters import (
    HIOBUY_1688_ID,
    LOCAL_1688_CLI_ID,
    NEXSCOPE_1688_LISTING_ID,
    NEXSCOPE_AMAZON_ID,
    NEXSCOPE_EBAY_ID,
    SERPAPI_AMAZON_ID,
    SERPAPI_EBAY_ID,
    SERPAPI_EBAY_DISCOVERY_ID,
    FunnelProviders,
    HioBuy1688Provider,
    Local1688CliProvider,
    Nexscope1688ListingProvider,
    NexscopeAmazonProvider,
    NexscopeEbayProvider,
    SerpApiEbayProvider,
    SerpApiAmazonProvider,
    SerpApiEbayDiscoveryProvider,
    build_provider_registry,
)

from proteus.providers.hiobuy import (
    HIOBUY_PROVIDER,
    ORDER_PREVIEW_ENDPOINT,
    PRODUCT_DETAIL_ENDPOINT,
    PRODUCT_SEARCH_ENDPOINT,
    HioBuyRequest,
    HioBuyResponse,
    collect_1688_supply,
)

from proteus.providers.local_1688_cli import (
    LOCAL_1688_CLI_PROVIDER,
    build_1688_query_pack,
    collect_1688_supplier,
    is_1688_cli_available,
    is_1688_cli_authenticated,
    is_valid_1688_offer_id,
    is_real_1688_url,
)

from proteus.providers.nexscope import (
    AMAZON_SEARCH_ENDPOINT,
    EBAY_SEARCH_ENDPOINT,
    NEXSCOPE_PROVIDER,
    SOURCE_METHOD,
    SUPPLY_1688_SEARCH_ENDPOINT,
    RestRequest,
    RestResponse,
    Transport,
    collect_1688_search,
    collect_amazon_search,
    collect_ebay_search,
)
from proteus.providers.registry import ProviderRegistry
from proteus.providers.serpapi_ebay import (
    SEARCH_ENDPOINT as SERPAPI_SEARCH_ENDPOINT,
    SERPAPI_EBAY_PROVIDER,
    SerpApiRequest,
    SerpApiResponse,
    collect_ebay_sold,
)
from proteus.providers.serpapi_amazon import (
    SERPAPI_AMAZON_PROVIDER,
    collect_amazon_competition,
)
from proteus.providers.serpapi_ebay_discovery import (
    SERPAPI_EBAY_DISCOVERY_PROVIDER,
    collect_ebay_sold_candidates,
)
from proteus.providers.ny_registration import (
    NHTSA_BATCH_ENDPOINT,
    NY_DATASET_ENDPOINT,
    NY_REGISTRATION_PROVIDER,
    NhtsaRequest,
    NhtsaResponse,
    NyRequest,
    NyResponse,
    collect_ny_registered_vehicle_proxy,
)

__all__ = [
    "AnnualSalesLookupRequest",
    "Capability",
    "CandidateDiscoveryRequest",
    "CheckStatus",
    "PartLookupRequest",
    "ProviderReadiness",
    "ReadinessCheck",
    "SupplyLookupRequest",
    "VehicleParcLookupRequest",
    "ProviderRegistry",
    "HIOBUY_1688_ID",
    "LOCAL_1688_CLI_ID",
    "NEXSCOPE_1688_LISTING_ID",
    "NEXSCOPE_AMAZON_ID",
    "NEXSCOPE_EBAY_ID",
    "SERPAPI_AMAZON_ID",
    "SERPAPI_EBAY_ID",
    "SERPAPI_EBAY_DISCOVERY_ID",
    "FunnelProviders",
    "HioBuy1688Provider",
    "Local1688CliProvider",
    "Nexscope1688ListingProvider",
    "NexscopeAmazonProvider",
    "NexscopeEbayProvider",
    "SerpApiEbayProvider",
    "SerpApiAmazonProvider",
    "SerpApiEbayDiscoveryProvider",
    "build_provider_registry",
    "AMAZON_SEARCH_ENDPOINT",
    "EBAY_SEARCH_ENDPOINT",
    "NEXSCOPE_PROVIDER",
    "SOURCE_METHOD",
    "SUPPLY_1688_SEARCH_ENDPOINT",
    "RestRequest",
    "RestResponse",
    "Transport",
    "collect_1688_search",
    "collect_amazon_search",
    "collect_ebay_search",
    "HIOBUY_PROVIDER",
    "ORDER_PREVIEW_ENDPOINT",
    "PRODUCT_DETAIL_ENDPOINT",
    "PRODUCT_SEARCH_ENDPOINT",
    "HioBuyRequest",
    "HioBuyResponse",
    "collect_1688_supply",
    "LOCAL_1688_CLI_PROVIDER",
    "build_1688_query_pack",
    "collect_1688_supplier",
    "is_1688_cli_available",
    "is_1688_cli_authenticated",
    "is_valid_1688_offer_id",
    "is_real_1688_url",
    "SERPAPI_SEARCH_ENDPOINT",
    "SERPAPI_EBAY_PROVIDER",
    "SerpApiRequest",
    "SerpApiResponse",
    "collect_ebay_sold",
    "SERPAPI_AMAZON_PROVIDER",
    "collect_amazon_competition",
    "SERPAPI_EBAY_DISCOVERY_PROVIDER",
    "collect_ebay_sold_candidates",
    "NHTSA_BATCH_ENDPOINT",
    "NY_DATASET_ENDPOINT",
    "NY_REGISTRATION_PROVIDER",
    "NhtsaRequest",
    "NhtsaResponse",
    "NyRequest",
    "NyResponse",
    "collect_ny_registered_vehicle_proxy",
]
